export const levelSP = {
		nodes: [
			{'id': 'sp_jundiai', 'label': 'Jundiai'},
			{'id': 'sp_barra_funda', 'label': 'Barra Funda'},
			{'id': 'sp_se', 'label': 'Sé'},
			{'id': 'sp_bras', 'label': 'Brás'},
			{'id': 'sp_amador_bueno', 'label': 'Amador Bueno'},
			{'id': 'sp_osasco', 'label': 'Osasco'},
			{'id': 'sp_pres_altino', 'label': 'Pres. Altino'},
			{'id': 'sp_pinheiros', 'label': 'Pinheiros'},
			{'id': 'sp_morumbi', 'label': 'Morumbi'},
			{'id': 'sp_santo_amaro', 'label': 'Santo Amaro'},
			{'id': 'sp_grajau', 'label': 'Grajaú'},
			{'id': 'sp_paraiso', 'label': 'Paraíso'},
			{'id': 'sp_ana_rosa', 'label': 'Ana Rosa'},
			{'id': 'sp_paulista', 'label': 'Paulista'},
			{'id': 'sp_vila_madalena', 'label': 'Vila Madalena'},
			{'id': 'sp_butanta', 'label': 'Butantã'},
			{'id': 'sp_tamanduatei', 'label': 'Tamanduateí'},
			{'id': 'sp_rio_grande_serra', 'label': 'Rio Grande da Serra'},
			{'id': 'sp_santo_andre', 'label': 'Santo André'},
			{'id': 'sp_sao_mateus', 'label': 'São Mateus'},
			{'id': 'sp_capao_redondo', 'label': 'Capão Redondo'},
			{'id': 'sp_tucuruvi', 'label': 'Tucuruvi'},
			{'id': 'sp_vila_prudente', 'label': 'Vila Prudente'},
			{'id': 'sp_republica', 'label': 'República'},
			{'id': 'sp_estudantes', 'label': 'Estudantes'},
			{'id': 'sp_luz', 'label': 'Luz'},
		],
		edges:[
			{'from': 'sp_jundiai', 'to': 'sp_barra_funda', 'label': '0'},
			{'from': 'sp_barra_funda', 'to': 'sp_jundiai', 'label': '0'},
			{'from': 'sp_barra_funda', 'to': 'sp_luz', 'label': '0'},
			{'from': 'sp_amador_bueno', 'to': 'sp_osasco', 'label': '0'},
			{'from': 'sp_osasco', 'to': 'sp_amador_bueno', 'label': '0'},
			{'from': 'sp_osasco', 'to': 'sp_pres_altino', 'label': '0'},
			{'from': 'sp_pres_altino', 'to': 'sp_barra_funda', 'label': '0'},
			{'from': 'sp_osasco', 'to': 'sp_pres_altino', 'label': '0'},
			{'from': 'sp_pres_altino', 'to': 'sp_pinheiros', 'label': '0'},
			{'from': 'sp_pinheiros', 'to': 'sp_morumbi', 'label': '0'},
			{'from': 'sp_morumbi', 'to': 'sp_santo_amaro', 'label': '0'},
			{'from': 'sp_capao_redondo', 'to': 'sp_santo_amaro', 'label': '0'},
			{'from': 'sp_santo_amaro', 'to': 'sp_capao_redondo', 'label': '0'},
			{'from': 'sp_grajau', 'to': 'teste2', 'sp_santo_amaro': '0'},
			{'from': 'sp_santo_amaro', 'to': 'sp_grajau', 'label': '0'},
			{'from': 'sp_morumbi', 'to': 'sp_santo_andre', 'label': '0'},
			{'from': 'sp_santo_andre', 'to': 'sp_sao_mateus', 'label': '0'},
			{'from': 'sp_sao_mateus', 'to': 'sp_santo_andre', 'label': '0'},
			{'from': 'sp_morumbi', 'to': 'sp_ana_rosa', 'label': '0'},
			{'from': 'sp_ana_rosa', 'to': 'sp_paraiso', 'label': '0'},
			{'from': 'sp_paraiso', 'to': 'sp_se', 'label': '0'},
			{'from': 'sp_se', 'to': 'sp_luz', 'sp_luz': '0'},
			{'from': 'sp_luz', 'to': 'sp_tucuruvi', 'label': '0'},
			{'from': 'sp_tucuruvi', 'to': 'sp_luz', 'label': '0'},
			{'from': 'sp_ana_rosa', 'to': 'sp_tamanduatei', 'label': '0'},
			{'from': 'sp_tamanduatei', 'to': 'sp_vila_prudente', 'label': '0'},
			{'from': 'sp_vila_prudente', 'to': 'sp_tamanduatei', 'label': '0'},
			{'from': 'sp_paraiso', 'to': 'sp_paulista', 'label': '0'},
			{'from': 'sp_paulista', 'to': 'sp_vila_madalena', 'label': '0'},
			{'from': 'sp_vila_madalena', 'to': 'sp_paulista', 'label': '0'},
			{'from': 'sp_paulista', 'to': 'sp_republica', 'label': '0'},
			{'from': 'sp_paulista', 'to': 'sp_pinheiros', 'label': '0'},
			{'from': 'sp_butanta', 'to': 'sp_pinheiros', 'label': '0'},
			{'from': 'sp_pinheiros', 'to': 'sp_butanta', 'label': '0'},
			{'from': 'sp_republica', 'to': 'sp_luz', 'label': '0'},
			{'from': 'sp_republica', 'to': 'sp_barra_funda', 'label': '0'},
			{'from': 'sp_republica', 'to': 'sp_se', 'label': '0'},
			{'from': 'sp_se', 'to': 'sp_bras', 'label': '0'},
			{'from': 'sp_bras', 'to': 'sp_tamanduatei', 'label': '0'},
			{'from': 'sp_tamanduatei', 'to': 'sp_rio_grande_serra', 'label': '0'},
			{'from': 'sp_rio_grande_serra', 'to': 'sp_tamanduatei', 'label': '0'},
			{'from': 'sp_bras', 'to': 'sp_estudantes', 'label': '0'},
			{'from': 'sp_estudantes', 'to': 'sp_bras', 'label': '0'},
			{'from': 'sp_grajau', 'to': 'sp_santo_amaro', 'label': '0'},
		]
  }

export const levelLDN = {
		nodes: [
			{'id': 'sp_jundiai', 'label': 'Jundiai'},
			{'id': 'sp_barra_funda', 'label': 'Barra Funda'},
			{'id': 'sp_se', 'label': 'Sé'},
			{'id': 'sp_bras', 'label': 'Brás'},
			{'id': 'sp_amador_bueno', 'label': 'Amador Bueno'},
			{'id': 'sp_osasco', 'label': 'Osasco'},
			{'id': 'sp_pres_altino', 'label': 'Pres. Altino'},
			{'id': 'sp_pinheiros', 'label': 'Pinheiros'},
			{'id': 'sp_morumbi', 'label': 'Morumbi'},
			{'id': 'sp_santo_amaro', 'label': 'Santo Amaro'},
			{'id': 'sp_grajau', 'label': 'Grajaú'},
			{'id': 'sp_paraiso', 'label': 'Paraíso'},
			{'id': 'sp_ana_rosa', 'label': 'Ana Rosa'},
			{'id': 'sp_paulista', 'label': 'Paulista'},
			{'id': 'sp_vila_madalena', 'label': 'Vila Madalena'},
			{'id': 'sp_butanta', 'label': 'Butantã'},
			{'id': 'sp_tamanduatei', 'label': 'Tamanduateí'},
			{'id': 'sp_rio_grande_serra', 'label': 'Rio Grande da Serra'},
			{'id': 'sp_santo_andre', 'label': 'Santo André'},
			{'id': 'sp_sao_mateus', 'label': 'São Mateus'},
			{'id': 'sp_capao_redondo', 'label': 'Capão Redondo'},
			{'id': 'sp_tucuruvi', 'label': 'Tucuruvi'},
			{'id': 'sp_vila_prudente', 'label': 'Vila Prudente'},
			{'id': 'sp_republica', 'label': 'República'},
			{'id': 'sp_estudantes', 'label': 'Estudantes'},
			{'id': 'sp_luz', 'label': 'Luz'},
		],
		edges:[
			{'from': 'sp_jundiai', 'to': 'sp_barra_funda', 'label': '0'},
			{'from': 'sp_barra_funda', 'to': 'sp_luz', 'label': '0'},
			{'from': 'sp_amador_bueno', 'to': 'sp_osasco', 'label': '0'},
			{'from': 'sp_osasco', 'to': 'sp_pres_altino', 'label': '0'},
			{'from': 'sp_pres_altino', 'to': 'sp_barra_funda', 'label': '0'},
			{'from': 'sp_osasco', 'to': 'sp_pres_altino', 'label': '0'},
			{'from': 'sp_pres_altino', 'to': 'sp_pinheiros', 'label': '0'},
			{'from': 'sp_pinheiros', 'to': 'sp_morumbi', 'label': '0'},
			{'from': 'sp_morumbi', 'to': 'sp_santo_amaro', 'label': '0'},
			{'from': 'sp_capao_redondo', 'to': 'sp_santo_amaro', 'label': '0'},
			{'from': 'sp_grajau', 'to': 'teste2', 'sp_santo_amaro': '0'},
			{'from': 'sp_morumbi', 'to': 'sp_santo_andre', 'label': '0'},
			{'from': 'sp_santo_andre', 'to': 'sp_sao_mateus', 'label': '0'},
			{'from': 'sp_morumbi', 'to': 'sp_ana_rosa', 'label': '0'},
			{'from': 'sp_ana_rosa', 'to': 'sp_paraiso', 'label': '0'},
			{'from': 'sp_paraiso', 'to': 'sp_se', 'label': '0'},
			{'from': 'sp_se', 'to': 'sp_luz', 'sp_luz': '0'},
			{'from': 'sp_luz', 'to': 'sp_tucuruvi', 'label': '0'},
			{'from': 'sp_ana_rosa', 'to': 'sp_tamanduatei', 'label': '0'},
			{'from': 'sp_tamanduatei', 'to': 'sp_vila_prudente', 'label': '0'},
			{'from': 'sp_paraiso', 'to': 'sp_paulista', 'label': '0'},
			{'from': 'sp_paulista', 'to': 'sp_vila_madalena', 'label': '0'},
			{'from': 'sp_paulista', 'to': 'sp_republica', 'label': '0'},
			{'from': 'sp_paulista', 'to': 'sp_pinheiros', 'label': '0'},
			{'from': 'sp_butanta', 'to': 'sp_pinheiros', 'label': '0'},
			{'from': 'sp_republica', 'to': 'sp_luz', 'label': '0'},
			{'from': 'sp_republica', 'to': 'sp_barra_funda', 'label': '0'},
			{'from': 'sp_republica', 'to': 'sp_se', 'label': '0'},
			{'from': 'sp_se', 'to': 'sp_bras', 'label': '0'},
			{'from': 'sp_bras', 'to': 'sp_tamanduatei', 'label': '0'},
			{'from': 'sp_tamanduatei', 'to': 'sp_rio_grande_serra', 'label': '0'},
			{'from': 'sp_bras', 'to': 'sp_estudantes', 'label': '0'},
			{'from': 'sp_grajau', 'to': 'sp_santo_amaro', 'label': '0'},
		]
  }

